### PR TITLE
Structure repo for collaboration

### PR DESCRIPTION
**Pull request by jvmncs**
This PR prepares the repo for collaborative development. Most important would be the collaboration guidelines I added @ `docs/collaboration.md`. The highlights of that doc are:
- Use `torchlib/` for torch-specific code, `tflib/` for TF-specific code.
- Code in the `common/` lib should not require heavy dependencies. There is a TODO to remove the ipynb dependency from the folder.

Secondly, I've included a script that takes the train/test data and allocates it to a variable number of training/testing clients. If you want to simulate federated experiments, you should use this script to generate data for each client. This should allow for reproducible results across implementations.

Special care has been taken to ensure the git history has clear & comprehensive descriptions of all changes, so check that out for any other details.

### CODE REVIEW

**Comment by jvmncs** [comment]
I just realized I've forgotten `train_federated.py`. This will unfortunately break the dataloader import statement from that file. I can go ahead and fix that once any pending changes are on master (or vice-versa, if you prefer)

**Comment by gkaissis** [comment]
@jvmncs thanks for the PR! Should we merge this into master and deprecate the other branches? I'm not sure what changes @LaRiffle and @a1302z were still planning. Can you guys please comment? I like the idea of common utils/data folders with separate modules for TF/PySyft.

**Comment by jvmncs** [comment]
>Should we merge this into master and deprecate the other branches?
I would suggest we merge/rebase with other branches. It should be straightforward, since most of what I did was move files around (outside of the README). If they're close to merging, I can wait for those updates to land on master, or we can merge this one and have them rebase their work on the new master branch.

**Comment by jvmncs** [comment]
Yep, this is definitely meant to be a PR for starting a discussion :)

>Should we merge this into master and deprecate the other branches?

If we like it, we can merge/rebase with other branches. If they're close to merging, I can wait for those updates to land on master, or we can merge this one and have them rebase their work on the new master branch.

**Comment by jvmncs** [comment]
@a1302z and I have chatted about this, and we aim to move forward. he's merged his work into master, and I've just rebased onto his work to make it align with this repo structure.

**Pull request merged**
